# This is a basic workflow to help you get started with Actions

name: Production CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types:
      - released

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy-staging:
    name: Deploy staging
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to namespace
        run: echo "Deploying " ${{ vars.NAMESPACE }}
  deploy-production:
    name: Deploy production
    needs: deploy-staging
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to namespace
        run: echo "Deploying " ${{ vars.NAMESPACE }}
